### ISSUE TITLE
doesn't build with Frames 0.6.1

### ISSUE THREAD

**Issue by unhammer** [dpkatz/HaskellGBM#3]
```
.stack-work/downloaded/t01DD7IMVy6a/src/LightGBM/DataSet.hs:76:8: error:
        Not in scope: type constructor or class ‘F.AsVinyl’
        Module ‘Frames’ does not export ‘AsVinyl’.
       |
    76 |      , F.AsVinyl ts
       |        ^^^^^^^^^
```

**Comment by unhammer** [comment]
(Maybe Frames should be optional / a separate packages?)
